<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="BankingCRM.Properties.Settings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Accounts" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccountNumber" Type="System.String" DbType="NChar(28) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CurrentBalance" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Account_Transaction" Member="Transactions" ThisKey="AccountNumber" OtherKey="AccountNumber" Type="Transaction" />
      <Association Name="Account_Customer" Member="Customers" ThisKey="AccountNumber" OtherKey="AccountNumber" Type="Customer" />
      <Association Name="Account_BankProduct" Member="BankProducts" ThisKey="AccountNumber" OtherKey="AccountNumber" Type="BankProduct" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="TransactionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NChar(28) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Transaction" Member="Account" ThisKey="AccountNumber" OtherKey="AccountNumber" Type="Account" IsForeignKey="true" />
      <Association Name="TransactionType_Transaction" Member="TransactionType" ThisKey="TransactionTypeId" OtherKey="TransactionTypeId" Type="TransactionType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransactionType" Member="TransactionTypes">
    <Type Name="TransactionType">
      <Column Name="TransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="TransactionType_Transaction" Member="Transactions" ThisKey="TransactionTypeId" OtherKey="TransactionTypeId" Type="Transaction" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NChar(28)" CanBeNull="true" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Account_Customer" Member="Account" ThisKey="AccountNumber" OtherKey="AccountNumber" Type="Account" IsForeignKey="true" />
      <Association Name="Address_Customer" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Addresses" Member="Addresses">
    <Type Name="Address">
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Address_Customer" Member="Customers" ThisKey="AddressId" OtherKey="AddressId" Type="Customer" />
    </Type>
  </Table>
  <Table Name="dbo.BankProducts" Member="BankProducts">
    <Type Name="BankProduct">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NChar(28) NOT NULL" CanBeNull="false" />
      <Association Name="Account_BankProduct" Member="Account" ThisKey="AccountNumber" OtherKey="AccountNumber" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
</Database>